### ISSUE TITLE
Notebook Error Ideas

### ISSUE THREAD

**Issue by anishprasanna** [amiratag/DataShapley#10]
Hi,
Unfortunately I keep getting this error:

Traceback (most recent call last):
  File "C:/Users/----------------------------y/main.py", line 47, in <module>
    directory=director, seed=0)
  File "C:\Users\-------------------------------\DShap.py", line 69, in __init__
    os.makedirs(directory)  
  File "C:\Users\--------------------------------os.py", line 220, in makedirs
    mkdir(name, mode)
FileNotFoundError: [WinError 2] The system cannot find the file specified: './temp'

Seems to be this chunk of code...

directory = './temp'
dshap = DShap(X,X_raw[:train_size], X_test, y_test, num_test,
              sources=None,
              sample_weight=None,
              model_family=model,
              metric='accuracy',
              overwrite=True,
              directory=directory, seed=0)

Is this to do with Windows?

**Comment by anishprasanna** [comment]
Setting directory to None gives the following error:

Traceback (most recent call last):
  File "C:/Users-------------------------main.py", line 47, in <module>
    directory=None, seed=0)
  File "C:\Users\---------------------------DShap.py", line 74, in __init__
    if len(set(self.y)) > 2:
AttributeError: 'DShap' object has no attribute 'y'
